### ISSUE TITLE
CardController에서 전역 변수 사용에 대해서

### ISSUE THREAD

**Issue by dotkebi** [back0331/OmniCard#1]
okky에서 링크 요청했었죠.
소스 한번 살펴봤습니다.

## 1.전역변수 지양
`controller`는 thread-safe하지 않기 때문에 전역변수에 쓰기 기능을 사용할 때는 의도치 않게 동작할 수 있습니다.
전역변수 `id`를 조회용도로 사용하실려고 한것 같은데, 위와 같은 이유로 좋지 않은 부분입니다.

## 2. `@ModelAttribute`
``` java
    @ModelAttribute
    public void setId(HttpServletRequest request) {
        HttpSession session = request.getSession();
        this.id = (String) session.getAttribute("id");
    }
```

이 부분도 디버그로 상태를 안찍어봐서 조금 의문이 드는 코드입니다.
`@ModelAttribute`를 리턴값이 있는 메서드에 지정하면 `model`에 해당 값을 넣어주는데, 위는 리턴값이 없는 void 타입이거든요. `cardController` 의 다른 메서드에서 활용할 메서드라면 private로 선언해서 활용하는게 좋을 것 같습니다.

## 3. 개선 방안
사실, 1,2 같은 말입니다. 해당 컨트롤러처럼 `form` 데이터를 받아서 처리하는 역할을 하는 경우에는
`@SessionAttributes`와 `@ModelAttribute`를 잘 활용하면 더 깔끔하게 처리할 수 있습니다.

``` java
@Controller
@SessionAttributes("cardCommand")
public class CardController {
	
    @ModelAttribute("cardCommand")
    public CardMemoCommand cardMemoCommand() {
        return new CardMemoCommand();
    }

    @RequestMapping(value="send.do", method=RequestMethod.POST)
    public ModelAndView send(
        @ModelAttribute("cardCommand") @Valid CardMemoCommand cardMemoCommand
        , BindingResult bindingResult
        , SessionStatus sessionStatus
    ) {
     if (bindingResult.hasErrors()) {
           // error 처리
            return ...; // form 작성 view로 다시 리턴
     }
        //save
        sessionStatus.setComplete();
        // 이후 로직
	return ...;
    }

```

`@Valid` 애노테이션 관련해서는 `Spring Validator`혹은 `JSR-303 빈 검증`에 대해서 공부해보시기 바랍니다.

도움이 되셨으면 좋겠네요.

**Comment by back0331** [comment]
@dotkebi 너무 감사드립니다!! 특히 @ModelAttribute가 붙은 setId메소드는 제 플젝 거의 모든 request에 session에 저장된 id값이 필요해서, controller가 호출될 때마다 실행되도록 한 것이었습니다. 근데 1에서 언급하신 부분을 보니 수정해야겠단 생각이 드네요....

원래 Spring공부때문에 하고 있는 플젝인데 방향을 잡아주셔서 감사합니다!!!

**Comment by dotkebi** [comment]
적당히 해결되셨으면 글타래는 닫겠습니다 :)
